"""giveaway start end dates

Revision ID: 9d7c9f6b603d
Revises: 14abf6340d75
Create Date: 2026-02-06 19:13:01.702014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d7c9f6b603d'
down_revision: Union[str, Sequence[str], None] = '14abf6340d75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'giveaways',
        sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    )
    op.add_column(
        'giveaways',
        sa.Column('end_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    )
    op.alter_column('giveaways', 'start_date', server_default=None)
    op.alter_column('giveaways', 'end_date', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('giveaways', 'end_date')
    op.drop_column('giveaways', 'start_date')
    # ### end Alembic commands ###
