"""giveaway notes

Revision ID: cd6988460967
Revises: 9d7c9f6b603d
Create Date: 2026-02-06 19:49:53.565408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd6988460967'
down_revision: Union[str, Sequence[str], None] = '9d7c9f6b603d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giveaways', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('giveaways', 'notes')
    # ### end Alembic commands ###
